export const actionEnum = {
    RETREIVING_START: 'RETREIVING_START',
    RETREIVING_SUCCESS: 'RETREIVING_SUCCESS',
    RETREIVING_FAIL: 'RETREIVING_FAIL',

    SECTION_CREATE_START: 'SECTION_CREATE_START',
    SECTION_CREATE_SUCCESS: 'SECTION_CREATE_SUCCESS',
    SECTION_CREATE_FAIL: 'SECTION_CREATE_FAIL',
};